    <h3><?php esc_html_e('Customize order preview columns','OrderPro_domain'); ?> </h3><p><?php esc_html_e('Activate and prioritize columns','OrderPro_domain'); ?></p>
    <ul>
        <li data-position="<?php echo array_search('Product', array_keys($OrderPro_Column));  ?>" id="Product"><span class="dashicons dashicons-menu opicon sort"></span><?php esc_html_e('Product','woocommerce'); ?></span><img data="<?php if(empty($OrderPro_Column['Product'])){echo 'true';}else{echo $OrderPro_Column['Product'];}  ?>" class="opicon visibleicon" src="<?php echo $visible ?>"></li>
        <li data-position="<?php echo array_search('Quantity', array_keys($OrderPro_Column));  ?>" id="Quantity"><span class="dashicons dashicons-menu opicon sort"></span><?php esc_html_e('Quantity','woocommerce'); ?></span><img data="<?php if(empty($OrderPro_Column['Quantity'])){echo 'true';}else{echo $OrderPro_Column['Quantity'];}  ?>" class="opicon visibleicon" src="<?php echo $visible ?>"></li>
        <li data-position="<?php echo array_search('Image', array_keys($OrderPro_Column));  ?>" id="Image"><span class="dashicons dashicons-menu opicon sort"></span><?php esc_html_e('Image','woocommerce'); ?></span><img data="<?php if(empty($OrderPro_Column['Image'])){echo 'true';}else{echo $OrderPro_Column['Image'];}  ?>" class="opicon visibleicon" src="<?php echo $visible ?>"></li>
        <li data-position="<?php echo array_search('Total', array_keys($OrderPro_Column));  ?>" id="Total"><span class="dashicons dashicons-menu opicon sort"></span><?php esc_html_e('Total','woocommerce'); ?></span><img data="<?php if(empty($OrderPro_Column['Total'])){echo 'true';}else{echo $OrderPro_Column['Total'];}  ?>" class="opicon visibleicon" src="<?php echo $visible ?>"></li>
        <li data-position="<?php echo array_search('Category', array_keys($OrderPro_Column));  ?>" id="Category"><span class="dashicons dashicons-menu opicon sort"></span><?php esc_html_e('Category','woocommerce'); ?></span><img data="<?php if(empty($OrderPro_Column['Category'])){echo 'true';}else{echo $OrderPro_Column['Category'];}  ?>" class="opicon visibleicon" src="<?php echo $visible ?>"></li>
        <li data-position="<?php echo array_search('Stock', array_keys($OrderPro_Column));  ?>" id="Stock"><span class="dashicons dashicons-menu opicon sort"></span><?php esc_html_e('Stock','woocommerce'); ?></span><?php echo OSPO_premiumHTML ?><img data="<?php if(empty($OrderPro_Column['Stock'])){echo 'true';}else{echo $OrderPro_Column['Stock'];}  ?>" class="opicon visibleicon" src="<?php echo $visible ?>"></li>
        <li data-position="<?php echo array_search('Price', array_keys($OrderPro_Column));  ?>" id="Price"><span class="dashicons dashicons-menu opicon sort"></span><?php esc_html_e('Price','woocommerce'); ?></span><img data="<?php if(empty($OrderPro_Column['Price'])){echo 'true';}else{echo $OrderPro_Column['Price'];}  ?>" class="opicon visibleicon" src="<?php echo $visible ?>"></li>
        <li data-position="<?php echo array_search('ProductID', array_keys($OrderPro_Column));  ?>" id="ProductID"><span class="dashicons dashicons-menu opicon sort"></span><?php esc_html_e('ID','woocommerce'); ?></span><img data="<?php if(empty($OrderPro_Column['ProductID'])){echo 'true';}else{echo $OrderPro_Column['ProductID'];}  ?>" class="opicon visibleicon" src="<?php echo $visible ?>"></li>
        <li data-position="<?php echo array_search('tax', array_keys($OrderPro_Column));  ?>" id="tax"><span class="dashicons dashicons-menu opicon sort"></span><?php esc_html_e('Tax','woocommerce'); ?></span><img data="<?php if(empty($OrderPro_Column['tax'])){echo 'true';}else{echo $OrderPro_Column['tax'];}  ?>" class="opicon visibleicon" src="<?php echo $visible ?>"></li>
        <?php if(class_exists( 'WeDevs_Dokan' )): ?>
        <li data-position="<?php echo array_search('Vendor', array_keys($OrderPro_Column));  ?>" id="Vendor"><span class="dashicons dashicons-menu opicon sort"></span><?php esc_html_e('Vendor','dokan-lite'); ?></span><img data="<?php if(empty($OrderPro_Column['Vendor'])){echo 'true';}else{echo $OrderPro_Column['Vendor'];}  ?>" class="opicon visibleicon" src="<?php echo $visible ?>"></li>
        <?php endif; ?>
    </ul>